-- Create the weight_history table
    CREATE TABLE public.weight_history (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
      weight_kg NUMERIC(5, 2) NOT NULL,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
    );

    -- Enable Row Level Security (RLS) for the weight_history table
    ALTER TABLE public.weight_history ENABLE ROW LEVEL SECURITY;

    -- Create RLS policy for SELECT (users can view their own weight history)
    CREATE POLICY "Users can view their own weight history."
    ON public.weight_history FOR SELECT
    USING (auth.uid() = user_id);

    -- Create RLS policy for INSERT (users can add their own weight entries)
    CREATE POLICY "Users can insert their own weight entries."
    ON public.weight_history FOR INSERT
    WITH CHECK (auth.uid() = user_id);

    -- Create RLS policy for UPDATE (users can update their own weight entries - optional, but good practice)
    CREATE POLICY "Users can update their own weight entries."
    ON public.weight_history FOR UPDATE
    USING (auth.uid() = user_id);

    -- Create RLS policy for DELETE (users can delete their own weight entries - optional)
    CREATE POLICY "Users can delete their own weight entries."
    ON public.weight_history FOR DELETE
    USING (auth.uid() = user_id);