// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://dxdowyxzaukudukeanbx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4ZG93eXh6YXVrdWR1a2VhbmJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxOTI5NDksImV4cCI6MjA3NDc2ODk0OX0.393VmxzeBnjN9_yUIDQD-74y4gcRtb4WM6NQOLxxNhU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);